services:
  - type: web
    name: rok-bot-backend
    runtime: python
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
